// Centralized lesson ordering for each course.
// Edit this file to reorder, insert, or remove lessons.
// Each array lists lesson slugs (filenames without extension) in the order they should appear.

export const courseLessonOrder: Record<string, string[]> = {
  "git-and-github": [
    "introduction",
    "git-what-it-is-and-why-it-exists",
    "git-creating-a-repository-and-making-your-first-commit",
    "git-understanding-status-diff-and-history",
    "git-branches-and-switching-work",
    "git-merging-branches",
    "git-amending-rebasing-and-force-pushing",
    "git-undoing-changes-safely",
    "github-what-it-is-and-how-it-relates-to-git",
    "github-connecting-a-local-repository-to-github",
    "github-cloning-and-syncing-work",
    "github-pull-requests",
    "github-code-review",
    "github-issues",
    "github-actions",
    "a-practical-everyday-workflow",
    "git-reference",
    "which-tools-and-workflows-should-you-use",
  ],
  terminal: [
    "introduction",
    "reading-and-understanding-commands",
    "navigating-the-filesystem",
    "creating-moving-and-removing-files",
    "viewing-and-inspecting-files",
    "search-and-discovery",
    "permissions-and-executables",
    "environment-and-shell-config",
    "pipes-redirection-and-shell-features",
    "editing-and-scripting",
  ],
  "npm-and-pnpm": [
    "introduction",
    "npm-what-it-is-and-why-it-exists",
    "npm-starting-a-project-and-installing-packages",
    "npm-running-scripts-and-understanding-package-lock",
    "npm-reference",
    "npm-and-pnpm-updating-packages-and-managing-versions",
    "pnpm-what-it-is-and-why-people-use-it",
    "npm-and-pnpm-global-tools-vs-local-tools",
    "pnpm-everyday-commands",
    "which-one-should-you-use",
    "how-npm-and-pnpm-compare",
    "npm-and-pnpm-workspaces-and-monorepos",
    "npm-and-pnpm-registries-scopes-and-publishing",
    "npm-and-pnpm-security-and-dependency-hygiene",
    "npm-and-pnpm-troubleshooting-common-problems",
    "pnpm-reference",
  ],
  typescript: [
    "what-is-typescript",
    "the-type-system-in-practice",
  ],
};
